### ISSUE TITLE
Improved text styles 

### ISSUE THREAD

**Issue by gingerbeardman** [mortenjust/webster-mac#3]
I think the dictionary could look a lot better, a lot closer to the typography used in the official dictionary.

You can also provide styles for the pop-up by specifying the class `html.apple_client-panel`

Take a look at my Emoji dictionary https://github.com/gingerbeardman/Emojipedia/blob/master/Emoji.css

I'll try to find time to have a go at this.

Thanks for the Dictionary!

**Comment by mortenjust** [comment]
Thanks! Would be awesome

**Comment by gsamat** [comment]
Maybe this will also solve dark theme issues we are having at the moment:
<img width="802" alt="Screenshot 2019-04-28 at 00 28 36" src="https://user-images.githubusercontent.com/705006/56855230-91705580-694c-11e9-9354-5850ae4c40cf.png">

<img width="802" alt="Screenshot 2019-04-28 at 00 28 50" src="https://user-images.githubusercontent.com/705006/56855232-99c89080-694c-11e9-80dd-d1ce07b13559.png">

**Comment by gingerbeardman** [comment]
Yes it would @gsamat

**Comment by lancelotly** [comment]
The same issue here on macOS Mojave v10.14.5 with the dark theme.

**Comment by lancelotly** [comment]
As suggested by @gingerbeardman , please add:

``` CSS
html {
  /* There is a style="background: white" on the html element we have to beat */
  background: transparent !important;
}

@media (prefers-dark-interface) {
  .hw {
    /* blue is more readable on the dark background than maroon */
    color: burlywood !important;
  }
  img {
    filter: invert(100%);
  }
}
```

to the /Contents/DefaultStyle.css to solve the problem in the dark mode on Mac
